import os
import pandas as pd

os.makedirs("../../data/processed_data/utci_country_monthly", exist_ok=True)
os.makedirs("job_reports", exist_ok=True)

combinationsfile = "../../data/processed_data/combinations.parquet"
popfile = "../../data/processed_data/populated.parquet"
combinations = pd.read_parquet(combinationsfile)
populated = pd.read_parquet("../../data/processed_data/populated.parquet")
countries = list(set(populated['adm0name']))
countries.sort()
ci = list(range(len(countries)))

rule all:
  input:
    "../../data/processed_data/utci_country_monthly.parquet",
    "../../data/processed_data/mortality_prediction.parquet",
    "../../results/mortality_prediction.pdf"

rule utci_countries:
  input:
    expand("{combinationsfile}", combinationsfile=combinationsfile),
    expand("{popfile}", popfile=popfile)
  output:
    "../../data/processed_data/utci_country_monthly/utci_monthly_{country}.parquet"
  shell:
    """
      python utci_country.py \
        --country {wildcards.country} \
        --popfile {popfile} \
        --combinations {combinationsfile} \
        --outfile {output}
    """

rule utci_countries_aggregate:
  input:
    expand("../../data/processed_data/utci_country_monthly/utci_monthly_{country}.parquet", country=ci),
  output:
    "../../data/processed_data/utci_country_monthly.parquet"
  run:
    import pandas as pd
    print(type(input))
    l = []
    for country in input:
      l.append(pd.read_parquet(country))
    out = pd.concat(l)
    out.to_parquet(str(output), compression="gzip")

rule mortality_prediction:
  input:
    "../../data/processed_data/utci_country_monthly.parquet"
  output:
    "../../data/processed_data/mortality_prediction.parquet",
    "../../results/mortality_prediction.pdf"
  notebook:
    "epi_mortality_modelling.ipynb"
